### ISSUE TITLE
[Epic] Refinamento da Aplicação

### ISSUE THREAD

**Issue by gabriosilva** [2023M5T1-Inteli/grupo3#138]
## Frontend

- [ ] Integrar Zona de Exclusão (alterar de retângulo para círculo)
- [ ] Adicionar tela com pontos de Parada
- [ ] Adicionar Filtros na tela de Resultados
- [ ] Adicionar Cards com informações adicionais (insights) na tela de resultados
- [ ] Error Handling
- [ ] Download/ Exportar Grafo

## Backend

- [ ] Error Handling
- [ ] Mensageria

## Java

- [ ] Fix AddEdges (otimizar)
- [ ] Otimizar integração com Neo4J
- [ ] Adicionar Pontos de Parada
- [ ] Incluir Raio de Curvatura
- [ ] Tunar Heurística
- [ ] Extrair Insights da rota (km percorridos, combustível, etc...)
- [ ] Testar pontos de exclusão
- [ ] Improve Error Handling
- [ ] Verificar modularidade/ divisão em classes do código (refinar)
- [ ] Verificar o uso de variáveis globais
- [ ] Spring MVC 
- [ ] Mensageria
