### ISSUE TITLE
[Epic] Implementar Documentação

### ISSUE THREAD

**Issue by gabriosilva** [2023M5T1-Inteli/grupo3#140]
## UI/UX/Geral

- [ ] Adicionar Wireframe, Guia de Estilo e Design de Interface
- [ ] Testes de Usabilidade
- [ ] Análise de Dados (conferir)
- [ ] Arquitetura do Sistema

## Frontend
- [ ] Manual de implementação
- [ ] Manual do Administrador

## Backend
- [ ]  Documentar Modelos do banco de dados
- [ ]  Manual de Implementação
- [ ] Manual do Administrador

## Java
- [ ] Manual de Implementação
- [ ] Manual do Administrador
