### ISSUE TITLE
[Epic] Deploy da Solução

### ISSUE THREAD

**Issue by gabriosilva** [2023M5T1-Inteli/grupo3#141]
## Frontend
- [ ] Deploy do Frontend na Vercecl

## Backend
- [ ] Deploy da API

## Java
- [ ] Deploy da API e arquivos DT2
